version: '3'

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        driver: ${VOLUMES_DRIVER}


services:
    workspace:
        build:
            context: "${WORKSPACE_PATH}"
            args:
                - AMZN_LINUX_VER=${AMZN_LINUX_VER}
                - PHP_VER=${PHP_VER}
        volumes:
            - "${WORKSPACE_PATH}:/var/www"
        tty: true
        networks:
            - frontend
            - backend
    mysql:
        build:
            context: "${MYSQL_PATH}"
            args:
                - MYSQL_VER_DOT=${MYSQL_VER_DOT}
                - MYSQL_VER=${MYSQL_VER}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_TZ=${MYSQL_TZ}
        volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
            - ${LOG_PATH}/mysql:/var/log/mysql
        ports:
            - "${MYSQL_PORT}:3306"
<<<<<<< HEAD
        networks:
            - backend
=======
>>>>>>> 9e796d9e9f3cf5c0946858d5cfa4747e127b0c17
